SET FEEDBACK OFF
SET LINESIZE 150
SET PAGESIZE 40

PROMPT --> DEBUT DU SCRIPT

REM ** Requête SQL de création des tables **

DROP TABLE USERS CASCADE CONSTRAINTS PURGE
/
DROP TABLE DOCUMENTS CASCADE CONSTRAINTS PURGE
/

PROMPT CREATION DES TABLES

CREATE TABLE USERS
(
	idUser INTEGER CONSTRAINT pk_idUser PRIMARY KEY,
	loginUser VARCHAR2(20),
	passwordUser VARCHAR2(10)
)
/

CREATE TABLE DOCUMENTS
(
	idDoc INTEGER CONSTRAINT pk_idDoc PRIMARY KEY,
	titreDoc VARCHAR2(50),
	auteurDoc VARCHAR2(20),
	typeDoc INTEGER,
	NumEmprunteur INTEGER
)
/

ALTER TABLE DOCUMENTS
ADD CONSTRAINT fk_NumEmprunteur
	FOREIGN KEY(NumEmprunteur)
	REFERENCES USERS(idUser)
	ON DELETE CASCADE

REM ** Ordres SQL de création de Séquences  **

PROMPT CREATION DES SEQUENCES

DROP SEQUENCE seq_users
/
DROP SEQUENCE seq_doc
/
CREATE SEQUENCE seq_users start with 0 Minvalue 0
/
CREATE SEQUENCE seq_doc start with 0 Minvalue 0
/

PROMPT --> SCRIPT COMPLETEMENT TERMINE

commit;

SET FEEDBACK ON
