SET FEEDBACK OFF
SET LINESIZE 150
SET PAGESIZE 40

PROMPT --> DEBUT DU SCRIPT

REM ** Requête SQL de création des tables **

DROP TABLE USERS CASCADE CONSTRAINTS PURGE
/
DROP TABLE DOCUMENTS CASCADE CONSTRAINTS PURGE
/

CREATE TABLE USERS
(
	idUser INTEGER CONSTRAINT pk_idUser PRIMARY KEY,
	loginUser VARCHAR2(20),
	passwordUser VARCHAR2(10)
)
/

CREATE TABLE DOCUMENTS
(
	idDoc INTEGER CONSTRAINT pk_idDoc PRIMARY KEY,
	titreDoc VARCHAR2(50),
	auteurDoc VARCHAR2(20)
	typeDoc INTEGER
)
/	